import { GoogleGenAI, Type } from "@google/genai";
import { ScheduleState, ShiftType, StaffRole, Staff, Site, ScheduleAssignment } from "../types";
import { getMonthDays, getRequiredLeaveDays } from "../utils/dateUtils";

export const optimizeScheduleWithAI = async (
  currentState: ScheduleState,
  draftAssignments: ScheduleAssignment[]
): Promise<ScheduleAssignment[]> => {
  // Use process.env.API_KEY directly.
  const ai = new GoogleGenAI({ apiKey: process.env.API_KEY });

  const days = getMonthDays(currentState.year, currentState.month);
  const requiredLeave = getRequiredLeaveDays(currentState.year, currentState.month);
  
  // Construct Context
  const sitesInfo = currentState.sites.map(s => `- ID: ${s.id}, Name: ${s.name}`).join('\n');
  
  const staffInfo = currentState.staff.map(s => {
    let base = `- ID: ${s.id}, Name: ${s.name}, Role: ${s.role}`;
    if (s.role === StaffRole.Regular) {
      base += `, Default Site: ${s.defaultSiteId}, Default Shift: ${s.defaultShift}`;
    } else if (s.role === StaffRole.Mobile) {
        let allowedShiftsStr = 'Day & Night';
        if (Array.isArray(s.allowedShifts) && s.allowedShifts.length > 0) {
             allowedShiftsStr = s.allowedShifts.join(' & ');
        }
        let allowedSitesStr = 'ALL';
        if (Array.isArray(s.allowedSiteIds) && s.allowedSiteIds.length > 0) {
            allowedSitesStr = s.allowedSiteIds.join(', ');
        }
        base += `, Allowed Shifts: [${allowedShiftsStr}], Allowed Sites: [${allowedSitesStr}]`;
    }
    return base;
  }).join('\n');

  const leaveRequestsInfo = currentState.leaveRequests.map(l => 
    `- Staff ${l.staffId} wants off on ${l.dateStr} (Designated: ${l.isDesignated})`
  ).join('\n');

  // We send the draft as a simplified list to save context, or full JSON if it fits. 
  // Given the size, full JSON is fine.
  const draftJson = JSON.stringify(draftAssignments);

  const prompt = `
    You are an expert Security Schedule Optimizer.
    
    I have a DRAFT SCHEDULE generated by a basic rule-based algorithm.
    Your goal is to REVIEW and OPTIMIZE this schedule to make it more "human-centric" and "organic", while strictly maintaining coverage and rules.

    **CURRENT PROBLEMS WITH DRAFT:**
    - The draft is too robotic (e.g., fixed patterns like 4-on-1-off).
    - It may have staff working too many consecutive days (e.g. 6 days).

    **OPTIMIZATION GOALS (Priority Order):**
    1. **Minimize Consecutive Work Days**: Ideally, Staff should work 3-4 days and then have a rest day. **Avoid 5+ consecutive work days** whenever possible.
    2. **STRICT LEAVE COUNT**: Regular Staff must have exactly ${requiredLeave} days off in total for this month. 
       - NOTE: The "Designated Leaves" listed below count towards this total ${requiredLeave}. 
       - DO NOT give them extra days off beyond ${requiredLeave} unless absolutely necessary.
    3. **Organic Patterns**: Introduce slight variations in the work/rest pattern so it feels less like a machine generated it.
    4. **Valid Coverage**: Every site/shift MUST be filled.
    5. **Mobile Staff Utilization**: Use Mobile staff efficiently to cover the Regular staff's off days.

    **HARD CONSTRAINTS (MUST NOT BREAK):**
    1. **Regular Staff**: MUST work their 'Default Site' and 'Default Shift' UNLESS they are assigned a rest day (replaced by Mobile). 
       - **CRITICAL**: A Night Shift Regular Staff MUST NEVER be assigned a Day Shift, and vice versa.
    2. **Mobile Staff**: 
       - **CRITICAL**: Can ONLY work at shifts they are explicitly allowed to (e.g. Night Mobile CANNOT work Day).
       - Can ONLY work at sites they are allowed to.
    3. **Rest Rules**:
       - No Night Shift (Date X) -> Day Shift (Date X+1). (Minimum 24hr rest after Night shift transition to Day).
       - No double booking.
    4. **Designated Leaves**: You MUST respect the specific leave requests listed below. Do not schedule staff on these days.

    **INPUT DATA:**
    YEAR: ${currentState.year}, MONTH: ${currentState.month + 1}
    Total Days: ${days.length}
    Target TOTAL Off Days Per Regular Staff: ${requiredLeave} (Includes Designated Leaves)

    **SITES:**
    ${sitesInfo}

    **STAFF:**
    ${staffInfo}

    **DESIGNATED LEAVES (Fixed - Count towards Total):**
    ${leaveRequestsInfo}

    **DRAFT SCHEDULE (To Optimize):**
    ${draftJson}

    **OUTPUT:**
    Return the fully optimized schedule as a JSON array of assignment objects.
    Format: [ { "dateStr": "YYYY-MM-DD", "siteId": "...", "shift": "Day"|"Night", "staffId": "..." }, ... ]
    Return ALL assignments for the whole month.
  `;

  try {
    const response = await ai.models.generateContent({
      model: 'gemini-3-flash-preview',
      contents: prompt,
      config: {
        responseMimeType: "application/json",
        responseSchema: {
          type: Type.ARRAY,
          items: {
            type: Type.OBJECT,
            properties: {
              dateStr: { type: Type.STRING },
              siteId: { type: Type.STRING },
              shift: { type: Type.STRING },
              staffId: { type: Type.STRING }
            }
          }
        }
      }
    });

    const jsonText = response.text;
    if (!jsonText) throw new Error("No response from AI");
    
    const parsed = JSON.parse(jsonText);
    
    if (Array.isArray(parsed)) {
        return parsed.map((item: any) => {
            // Basic parsing
            let shift = item.shift?.toLowerCase().includes('night') ? ShiftType.Night : ShiftType.Day;
            const staffId = item.staffId?.trim();
            const siteId = item.siteId?.trim();
            const dateStr = item.dateStr?.trim();

            const staffMember = currentState.staff.find(s => s.id === staffId);
            if (!staffMember) {
                // Unknown staff, discard
                return null;
            }

            // --- STRICT POST-PROCESSING ENFORCEMENT ---
            
            // 1. Regular Staff Constraints
            if (staffMember.role === StaffRole.Regular && staffMember.defaultSiteId === siteId) {
                // If working at default site, FORCE default shift to avoid hallucination
                if (staffMember.defaultShift) {
                    shift = staffMember.defaultShift; 
                }
            }

            // 2. Mobile Staff Constraints
            if (staffMember.role === StaffRole.Mobile) {
                // Check Shift Constraint
                if (staffMember.allowedShifts && staffMember.allowedShifts.length > 0) {
                    if (!staffMember.allowedShifts.includes(shift)) {
                        // AI assigned a prohibited shift (e.g. Day for Night Mobile)
                        console.warn(`Removed invalid shift for mobile staff ${staffMember.name}: assigned ${shift} but allowed ${staffMember.allowedShifts.join(',')}`);
                        return null; // Remove this assignment
                    }
                }

                // Check Site Constraint
                if (staffMember.allowedSiteIds && staffMember.allowedSiteIds.length > 0) {
                    if (!staffMember.allowedSiteIds.includes(siteId)) {
                        console.warn(`Removed invalid site for mobile staff ${staffMember.name}`);
                        return null; // Remove this assignment
                    }
                }
            }

            return {
                dateStr,
                siteId,
                shift,
                staffId
            };
        }).filter((item: any) => item !== null); // Filter out the nulls (invalid assignments)
    }

    return parsed;
  } catch (error) {
    console.error("AI Optimization Error:", error);
    throw error; // Let the caller handle the fallback
  }
};